config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: %i[show new create] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true, allow_blank: false
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :cocktail_id, :ingredient_id, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: %i[new create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<div class="card-test">
  <% @cocktails.each do |cocktail| %>
    <div class="card-container">
      <%= link_to cocktail.name, cocktail_path(cocktail), { class: "card-each" } %>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Create a new cocktail!</h2>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.submit "Submit cocktail", class: "btn btn-form" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1>Cocktail: <%= @cocktail.name %></h1>

<% @cocktail.doses.each do |dose| %>
<%= dose.description %>
<%= dose.ingredient.name %>
<% end %>

<h2>Add a new ingredient to this cocktail</h2>

app/views/doses/new.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Create a new cocktail!</h2>
    <%= simple_form_for [ @cocktail, @dose ] do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <%= f.submit "Submit ingredient", class: "btn btn-form" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wrapper">
      <div class="navbar-left">
      <%= image_tag "cocktail.jpg", alt: "Cocktail", class: "logo" %>
      <h1>Them Cocktails</h1>
      </div>
      <div class="navbar-right">
        <% unless controller_name == "cocktails" && action_name == "new" %>
          <%= link_to "Create a new cocktail", new_cocktail_path, class: "btn btn-create-cocktail" %>
        <% end %>
        <% unless controller_name == "cocktails" && action_name == "index" %>
          <%= link_to "Go back to cocktails list", root_path, class: "btn btn-homepage" %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>